### PR TITLE
#close57-fix_form_values

### LINKED ISSUE #57: fix_form_values
- [ ] update FormValues to have `name` `age` `level` `msg`. fix the naming in 
- [ ] 1- the type 
- [ ] 2- resigsters and other errors 
<br />

- [ ] correct level values from
```ts
const levels = ["Easy", "Normal", "Hard"];
``` 
to lowercase 
```ts
const levels = ["easy", "normal", "hard"];
```

<br />
<br />

- [ ] if item create failed do not reset() data fields. 
> remove it from `finally` and set it to the `try` block

### PR DESCRIPTION
**Pull request by rehabhussein69**
update  form

### CODE REVIEW

File: front/src/components/UserForm.tsx [hunk 1]
```diff
@@ -50,36 +50,36 @@ const UserFormDesign: React.FC = () => {
...
+       try {
+           const result = await fetch("/api/post/create", {
+               method: "POST",
+               headers: { "Content-Type": "application/json" },
+               body: JSON.stringify(data),
+           });
+   
+           if (result.ok) {
+               setSuccess(true);
+               resetFields = { ...data, Age:"" ,}; // Reset all fields except 'Age'
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]: `resetFields = { ...data, Age:"" ,}; // Reset all fields except 'Age'`
not required please remove

File: front/src/components/UserForm.tsx [hunk 2]
```diff
@@ -50,36 +50,36 @@ const UserFormDesign: React.FC = () => {
...
+           } else {
+               throw new Error();
+           }
+       } catch (e) {
+           setSuccess(false);
+           setError("Submission failed");
+       } finally {
+           setLoading(false);
+           reset(resetFields); // Reset form fields conditionally
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]: `reset(resetFields); // Reset form fields conditionally`
not required set back to `reset();`

File: front/src/components/UserForm.tsx [hunk 3]
```diff
@@ -170,10 +170,10 @@ const UserFormDesign: React.FC = () => {
                                           <TextField
                                                  label="Age"
                                                  type="date"
-                                                 {...register("birthDate", { required: "Date is Required" })}
+                                                 {...register("Age", { required: "Age is Required" })}
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]: "Age" is not correct ❌
"age" must be in lower case

File: front/src/components/UserForm.tsx [hunk 4]
```diff
@@ -170,10 +170,10 @@ const UserFormDesign: React.FC = () => {
...
                                                  InputLabelProps={{ shrink: true }}
-                                                 error={!!errors.birthDate}
-                                                 helperText={errors.birthDate?.message ? errors.birthDate?.message : " "}
+                                                 error={!!errors.Age}
+                                                 helperText={errors.Age?.message ? errors.Age?.message : " "}
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]: `error={!!errors.Age}` ❌
 `error={!!errors.age}`  ✅

File: front/src/components/UserForm.tsx [hunk 5]
```diff
@@ -30,12 +30,12 @@ const theme = createTheme({
...
-const levels = ["Easy", "Normal", "Hard"];
+const levels = ["easy", "normal", "hard"];
 
 type FormValues = {
        username: string;
-       birthDate: string;
-       level: string;
+       Age: Date;
+       level: "easy"|"normal"|"hard";
        message: string;
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]:
```ts
      ❌ username: string;
      ❌ Age: Date;
       level: "easy"|"normal"|"hard";
      ❌ message: string;
```

those are not correct to be sent to the backend they must be  :
```ts
       name: string;
       age: Date;
       level: "easy"|"normal"|"hard";
       msg: string;
```

File: front/src/components/UserForm.tsx [hunk 6]
```diff
@@ -155,7 +155,7 @@ const UserFormDesign: React.FC = () => {
                                           <TextField
                                                  label="Name"
                                                  {...register("username", {
```
Comment (DevAbdoTolba) [inline front/src/components/UserForm.tsx]: The most importnat part for the update is to set the `register()` value
it must be ` {...register("name", {`
all lower case

**Review by DevAbdoTolba — CHANGES_REQUESTED** [review]
Some changes are required.

please make sure the fields' names are all in lowercase. and to change for each field.

- [ ] type in FormValues
- [ ] register value
- [ ] error value for `error={}`
- [ ] error value for `helperText={}`

**Review by DevAbdoTolba — APPROVED** [review]
LGTM 👍
